name: Fly Deploy Staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: flyctl deploy --remote-only --config ./fly.staging.toml -e NCRS_COMMIT_HASH={{ env.git_hash }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}